#3 instruction to run the second code, as we are creating the image of all the code in this file to be deployed at once

services:
  pgdatabase: #servicename
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge


# ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw: 
# This line defines a volume mount. It maps the local directory ./ny_taxi_postgres_data
#  to the container's directory /var/lib/postgresql/data. The rw option indicates that the volume is mounted in read-write mode, allowing both reading from and writing to the volume.